#!/bin/bash
#
# THIS SCRIPT AUTOMATES THE EDITS REQUIRED TO EMBED THE GLADE-GENERATED INTERFACE
# DEFINITION FILE WITHIN A CHARACTER STRING.  DOING SO ALLOWS THE INTERFACE DEFINITION
# TO BE CONTAINED WITHIN THE EXECUTABLE AND THUS NOT REQUIRED AS AN ADDITIONAL
# DEPENDENCY WHEN DISTRIBUTING THE PROGRAM.
#
#

# DEFINE THE FILE TO BE CONVERTED
GLADEFILE="UnitConvert.ui"

# DEFINE NAME TO BE USED FOR FINAL OUTPUT
OUTPUTFILE="interface.ui"

# DEFINE THE FILE WITH THE FIRST LINE TO BE USED IN THE TRANSFORMED FILE
FIRSTLINEFILE="firstline.txt"

# DEFINE THE FILE WITH THE LAST LINE TO BE USED IN THE TRANSFORMED FILE
LASTLINEFILE="lastline.txt"

# REMOVE EXISTING TRANSFORMED FILE AND TEMPORARY FILE
rm -f $OUTPUTFILE

# CREATE TEMPORARY FILE AND INSERT FIRST LINE
touch tmp.ui
cat $FIRSTLINEFILE >> tmp.ui

# ADD CONTENTS OF GLADE-GENERATED FILE TO TEMPORARY FILE
cat $GLADEFILE >> tmp2.ui

# CHANGE " TO \" IN TEMPORARY FILE AND ADD \ TO THE END OF EACH LINE.  RESULT IS
# PLACED IN A SECOND TEMPORARY FILE
sed -e 's/"/\\"/g' tmp2.ui | sed -e 's/???/?\\?\\?/g' | sed -e 's/$/\\/g' >> tmp3.ui

# COMBINE FIRST TWO TEMPORARY FILES
cat tmp3.ui >> tmp.ui

# APPEND LAST LINE TO 2ND TEMPORARY FILE
cat $LASTLINEFILE >> tmp.ui

# COPY 2ND TEMPORARY FILE TO OUTPUT FILE
cp tmp.ui $OUTPUTFILE

# CLEAN UP TEMPORARY FILES
rm -f tmp.ui
rm -f tmp2.ui
rm -f tmp3.ui

